-- CreateEnum
CREATE TYPE "Budgets" AS ENUM ('TOTAL', 'RENT', 'UTILITIES', 'MAINTAINENCE', 'TRANSPORT', 'GROCERIES', 'HEALTH', 'SHOPPING', 'FOOD', 'ENTERTAINMENT', 'MISCELLANEOUS');

-- CreateTable
CREATE TABLE "Budget" (
    "id" SERIAL NOT NULL,
    "capacity" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "type" "Budgets" NOT NULL,

    CONSTRAINT "Budget_pkey" PRIMARY KEY ("id")
);
