import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Container, Grid, Theme } from "@radix-ui/themes";
import Sidebar from "./Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme appearance="dark">
          <Grid
            areas={{
              initial: '"main"',
              lg: '"aside main"',
            }}
            columns={{
              initial: "1fr",
              lg: "300px 1fr",
            }}
          >
            <Sidebar />
            {children}
          </Grid>
        </Theme>
      </body>
    </html>
  );
}
