import { Box, Grid, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Sidebar from "./Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <Theme accentColor="pink" radius="large">
            <Grid
              areas={{
                initial: '"main"',
                lg: '"aside main"',
              }}
              columns={{
                initial: "1fr",
                lg: "280px 1fr",
              }}
              className="min-h-screen"
            >
              <Sidebar />
              <Box gridArea="main">
                <Navbar />
                {children}
              </Box>
            </Grid>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
