describe('login and verify the dashboard', () => {
  it('verifies user login and dashboard', () => {
    cy.visit('https://my-expense-tracker-beta.vercel.app/')
    cy.contains('Expense Tracker')
    cy.contains('Login').click()
    cy.contains('Sign In to your account')
    cy.get(':nth-child(1) > .rt-TextFieldRoot > .rt-reset').type('test@xyz.com')
    cy.get(':nth-child(2) > .rt-TextFieldRoot > .rt-reset').type('Test@123')
    cy.get('.rt-BaseButton').click()
    cy.contains('Expense Tracker')
    cy.contains('Dashboard')
    cy.contains('Expenses')
    cy.contains('Budgets')
    cy.contains('Hi, test 👋')
    cy.contains('Here are your expenses at a glance.')
    cy.contains('Total Budget')
    cy.contains('Total Remaining')
    cy.contains('Total Spend')
    cy.contains('Last 7 Expenses')
    cy.contains('Recent Expenses')
  })
})