describe('add a budget', () => {
  it('verifies budget is added and displayed', () => {
    cy.visit('https://my-expense-tracker-beta.vercel.app/')
    cy.contains('Login').click()
    cy.get(':nth-child(1) > .rt-TextFieldRoot > .rt-reset').type('test2@xyz.com')
    cy.get(':nth-child(2) > .rt-TextFieldRoot > .rt-reset').type('Test@123')
    cy.get('.rt-BaseButton').click()
    cy.get('.rt-BaseButton.xl\\:hidden').click()
    cy.get('.rt-ContainerInner > .rt-Flex > [href="/main/budgets"]').click()
    cy.get('.rt-Heading').contains('Budgets')
    cy.get('.rt-BaseButton').contains('Add New Budget').click()
    cy.get('.rt-TextFieldRoot > .rt-reset').clear().type('500')
    cy.get('.rt-variant-solid').contains('Add').click()
    cy.get('.text-xl').contains('$ 500')
    cy.get('.rt-BaseCard > .rt-r-fd-column > .rt-Flex > :nth-child(1)').contains('$ 0 Spend')
    cy.get('.rt-BaseCard > .rt-r-fd-column > .rt-Flex > :nth-child(2)').contains('$ 500 Remaining')
    cy.get('.rt-BaseButton.xl\\:hidden').click()
    cy.get('.rt-ContainerInner > .rt-Flex > [href="/main"]').click()
    cy.get(':nth-child(1) > .rt-r-jc-space-between > .rt-r-fd-column').contains('$ 500')
    cy.get(':nth-child(2) > .rt-r-jc-space-between > .rt-r-fd-column').contains('$ 500')
  })
})