describe('add an expense', () => {
  it('verifies expense is added and displayed', () => {
    cy.visit('https://my-expense-tracker-beta.vercel.app/')
    cy.contains('Login').click()
    cy.get(':nth-child(1) > .rt-TextFieldRoot > .rt-reset').type('test2@xyz.com')
    cy.get(':nth-child(2) > .rt-TextFieldRoot > .rt-reset').type('Test@123')
    cy.get('.rt-BaseButton').click()
    cy.get('.rt-BaseButton.xl\\:hidden').click()
    cy.get('.rt-ContainerInner > .rt-Flex > [href="/main/expenses"]').click()
    cy.get('.rt-Heading').contains('Expenses')
    cy.get('.rt-variant-solid').contains('Add New Expense').click()
    cy.get('.rt-TextFieldRoot > .rt-reset').clear().type('100')
    cy.get('button[type="button"][aria-haspopup="menu"]').contains('Category').click()
    cy.get('.rt-BaseMenuViewport > :nth-child(2)').contains('HOME').click()
    cy.get('.rt-TextAreaRoot > .rt-reset').type('Test expense for home category')
    cy.get('.rt-r-jc-end > .rt-variant-solid').contains('Add').click()
    cy.get('.rt-TableBody > .rt-TableRow > .hidden > .rt-Flex').contains('Test expense for home category')
    cy.get('.text-nowrap > .rt-Flex').contains('$100')
    cy.get('.rt-BaseButton.xl\\:hidden').click()
    cy.get('.rt-ContainerInner > .rt-Flex > [href="/main"]').click()
    cy.get(':nth-child(1) > .rt-r-jc-space-between > .rt-r-fd-column').contains('$ 500')
    cy.get(':nth-child(2) > .rt-r-jc-space-between > .rt-r-fd-column').contains('$ 400')
    cy.get(':nth-child(3) > .rt-r-jc-space-between > .rt-r-fd-column').contains('$ 100')
  })
})