describe('delete an expense', () => {
  it('verifies expense is deleted and dashboard is updated', () => {
    cy.visit('https://my-expense-tracker-beta.vercel.app/')
    cy.contains('Login').click()
    cy.get(':nth-child(1) > .rt-TextFieldRoot > .rt-reset').type('test2@xyz.com')
    cy.get(':nth-child(2) > .rt-TextFieldRoot > .rt-reset').type('Test@123')
    cy.get('.rt-BaseButton').click()
    cy.get('.rt-BaseButton.xl\\:hidden').click()
    cy.get('.rt-ContainerInner > .rt-Flex > [href="/main/expenses"]').click()
    cy.get('.rt-Heading').contains('Expenses')
    cy.get('.rt-TableBody > .rt-TableRow > .hidden > .rt-Flex').contains('Test expense for home category')
    cy.get('.text-nowrap > .rt-Flex').contains('$100')
    cy.get(':nth-child(5) > .rt-Flex > .rt-reset').click()
    cy.contains('Delete').click()
    cy.get('.rt-r-weight-bold').contains('No Expenses')
    cy.get('.rt-BaseButton.xl\\:hidden').click()
    cy.get('.rt-ContainerInner > .rt-Flex > [href="/main"]').click()
    cy.get(':nth-child(1) > .rt-r-jc-space-between > .rt-r-fd-column').contains('$ 500')
    cy.get(':nth-child(2) > .rt-r-jc-space-between > .rt-r-fd-column').contains('$ 500')
    cy.get(':nth-child(3) > .rt-r-jc-space-between > .rt-r-fd-column').contains('$ 0')
  })
})